name: flutter_notebook
description: "This is a flutter notebook that leverages localstorage to store user's notes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_quill: ^11.2.0
  sqflite: ^2.4.2
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.1
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  drift_dev: ^2.27.0

flutter:
  uses-material-design: true
  assets:
    - assets/